name: quran_app
description: "A quran app that helps you to read quran"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  
  # l10n & date format
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  slang: ^3.31.2
  slang_flutter: ^3.31.0

  dio: ^5.4.3+1
  dio_smart_retry: ^6.0.0
  pretty_dio_logger: ^1.4.0

  # download assets
  download_assets: ^3.2.0

  # riverpod & hooks (state management)
  flutter_hooks: ^0.20.0
  flutter_riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6

  # routing
  go_router: ^12.1.3

  # data persistence
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  get_secure_storage: ^1.0.4

  # models & serialization
  equatable: ^2.0.5

  # responsive
  flutter_screenutil: ^5.8.4

  # animation
  animations: ^2.0.11
  flutter_animate: ^4.2.0

  # splash screen
  flutter_native_splash: ^2.3.1

  # logging
  quick_log: ^5.3.1

  # ui
  flutter_svg: ^2.0.7
  json_annotation: ^4.9.0
  collection: ^1.18.0
  internet_connection_checker_plus: ^2.5.0
  path: ^1.9.0
  path_provider: ^2.1.4
  carousel_slider_plus: ^7.0.1
  material_symbols_icons: ^4.2785.1
  expandable: ^5.0.1
  modal_bottom_sheet: ^3.0.0
  bottom_sheet: ^4.0.4
  wolt_modal_sheet: ^0.9.3
  smooth_sheets: ^0.10.0
  easy_sticky_header: ^1.1.1
  sqflite: ^2.3.3+2
  riverpod: ^2.5.1
  skeletonizer: ^1.4.2
  flutter_archive: ^6.0.3
  keep_screen_on: ^3.0.0
  # custom_sliding_segmented_control: ^1.8.3
  # timeago: ^3.6.1
  # timeago_flutter: ^3.6.0
  # skeletonizer: ^1.3.0
  # audioplayers: ^6.0.0
  # keep_screen_on: ^3.0.0
  # visibility_detector: ^0.4.0+2
  # expandable_page_view: ^1.0.17
  # fluttertoast: ^8.2.4
  # auto_size_text_plus: ^3.0.1

  # utilities
  # timeago: ^3.6.0
  # flutter_local_notifications: ^17.0.0
  # internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_lint: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  slang_build_runner: ^3.31.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  image: "assets/images/logo.png"
  color: "#FFFFFF"
  android: true
  ios: true

  android_12:
    image: "assets/images/logo.png"
    color: "#FFFFFF"


flutter_gen:
  output: lib/assets/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/lottie/
    - assets/db/

  fonts:
    - family: UthmanTN
      fonts:
        - asset: assets/fonts/UthmanTN/UthmanTN-Regular.ttf
          weight: 400
        - asset: assets/fonts/UthmanTN/UthmanTN-Bold.ttf
          weight: 700
    - family: UthmanicHafs
      fonts:
        - asset: assets/fonts/UthmanicHafs/UthmanicHafs.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
